"""second

Revision ID: 052597011587
Revises: 
Create Date: 2022-08-15 16:09:20.939549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052597011587'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_color', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
