"""quit favorite_color

Revision ID: 8d8ef9cc4e3e
Revises: c3e906232308
Create Date: 2022-08-16 15:43:07.489255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8ef9cc4e3e'
down_revision = 'c3e906232308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_color', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
